const scenes = [
	{
		monthIdx: 7,
		month: "08August",
		scpt: "augclrscpt",
		name: "CORAL",
		title: "Aquarius - Clear",
		sound: "CORAL",
		maxVolume: 0.25,
		remap: {
			0: [0, 0, 0],
		},
		offsetX: 0,
		offsetY: -35,
	},
	{
		monthIdx: 9,
		month: "10October",
		scpt: "octbegclrscpt",
		name: "V05AM",
		title: "Haunted Ruins - Clear",
		sound: "V13",
		remap: {
			254: [0, 0, 0],
			0: [11, 11, 11],
		},
		offsetX: 0,
		offsetY: 0,
	},
	{
		month: "10October",
		scpt: "octrainscpt",
		name: "V05RAIN",
		title: "Haunted Ruins - Rain",
		sound: "V05RAIN",
		remap: {
			254: [0, 0, 0],
			0: [11, 11, 11],
		},
		offsetX: 0,
		offsetY: 0,
	},
	{
		monthIdx: 4,
		month: "05May",
		scpt: "MAYCLRSCPT",
		name: "V08",
		title: "Jungle Waterfall - Clear",
		sound: "V08",
		maxVolume: 0.25,
		offsetX: 0,
		offsetY: 0,
	},
	{
		month: "05May",
		scpt: "MAYCLDYSCPT",
		name: "V08",
		title: "Jungle Waterfall - Cloudy",
		sound: "V08",
		maxVolume: 0.25,
		offsetX: 0,
		offsetY: 0,
	},
	{
		month: "05May",
		scpt: "MAYRAINSCPT",
		name: "V08RAIN",
		title: "Jungle Waterfall - Rain",
		sound: "V08RAIN",
		offsetX: 0,
		offsetY: 0,
	},
	{
		monthIdx: 10,
		month: "11November",
		scpt: "novclrscpt",
		name: "V16",
		title: "Mirror Pond - Clear",
		sound: "V16",
		offsetX: 0,
		offsetY: 0,
	},
	{
		month: "11November",
		scpt: "novrainscpt",
		name: "V16RAIN",
		title: "Mirror Pond - Rain",
		sound: "V16RAIN",
		offsetX: 0,
		offsetY: 0,
	},
	{
		monthIdx: 1,
		month: "02February",
		scpt: "febclrscpt",
		name: "V19",
		title: "Mountain Stream - Clear",
		sound: "V19",
		offsetX: 0,
		offsetY: -100,
	},
	{
		month: "02February",
		scpt: "febcldyscpt",
		name: "V19",
		title: "Mountain Stream - Cloudy",
		sound: "V19",
		offsetX: 0,
		offsetY: 0,
	},
	{
		monthIdx: 5,
		month: "06June",
		scpt: "jundayscpt",
		name: "V20JOE",
		title: "Crystal Caves - Clear",
		sound: "V20",
		offsetX: 0,
		offsetY: 0,
	},
	{
		monthIdx: 6,
		month: "07July",
		scpt: "julyclearscpt",
		name: "V25",
		title: "Desert - Clear",
		sound: "V25HEAT",
		offsetX: 0,
		offsetY: -100,
	},
	{
		month: "07July",
		scpt: "julycloudyscpt",
		name: "V25",
		title: "Desert - Cloudy",
		sound: "V25HEAT",
		offsetX: 0,
		offsetY: 0,
	},
	{
		month: "01January",
		scpt: "janclrscpt",
		name: "V26",
		title: "Winter Forest - Clear",
		sound: "V13",
		offsetX: 0,
		offsetY: -50,
	},
	{
		monthIdx: 0,
		month: "01January",
		scpt: "jansnowscpt",
		name: "V26SNOW",
		title: "Winter Forest - Snow",
		sound: "V05RAIN",
		maxVolume: 0.25,
		offsetX: 0,
		offsetY: -50,
	},
	{
		monthIdx: 8,
		month: "09September",
		scpt: "SEPTCLRCUMSCPT",
		name: "V29",
		title: "Seascape - Clear",
		sound: "V29",
		remap: {
			252: [11, 11, 11],
		},
		offsetX: 0,
		offsetY: -100,
	},
	{
		month: "09September",
		scpt: "SEPTCLDYSCPT",
		name: "V29",
		title: "Seascape - Cloudy",
		sound: "V29",
		remap: {
			252: [11, 11, 11],
		},
		offsetX: 0,
		offsetY: -100,
	},
	{
		monthIdx: 3,
		month: "04April",
		scpt: "aprclrscpt",
		name: "V30",
		title: "Deep Forest - Clear",
		sound: "V30",
		maxVolume: 0.25,
		offsetX: 0,
		offsetY: -50,
	},
	{
		month: "04April",
		scpt: "aprrainscpt",
		name: "V30RAIN",
		title: "Deep Forest - Rain",
		sound: "V30RAIN",
		offsetX: 0,
		offsetY: -50,
	},
];
